export const routes = {
  home: "/",
  dashboardAdmin: "/dashboard/admin",
  categoryAdmin: "/dashboard/admin/categories",
  productAdmin: "/dashboard/admin/products",
  orderAdmin: "/dashboard/admin/orders",
  orderUser: "/order",
  account: "/account",
  product: "/products/:slug",
  category: "/categories/:slug",
  categories: "/categories",
  products: "/products",
  cart: "/cart",
  payment: "/payment",
};
